### ISSUE TITLE
Create a process to download and import location & review data

### ISSUE THREAD

**Issue by travissouthard** [CodeForPhilly/third-places#22]
# Overview

Create a process to fetch locations and reviews from the [Yelp API](https://docs.developer.yelp.com/docs/fusion-intro), and then process that data to import it as models in Django. 

# Context

Blocked by #8, but can be branched off of #21

# Suggested solution (optional)

Once the process is figured out, add a script to automate this and add to the work being done on #5

**Comment by mdarkcity** [comment]
Could I take this one on?

**Comment by travissouthard** [comment]
Yeah! I was going to ask for your help on this since you have done the most poking at the Yelp API, but yeah, go for it!
