### ISSUE TITLE
Create Django models for location and user

### ISSUE THREAD

**Issue by travissouthard** [CodeForPhilly/third-places#8]
# Overview

Create django models for `location`, `tags`, and `user` objects that we will use for the endpoints in the app. User can [extend the native user model](https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#abstractbaseuser) in django.

This work should include [making the migrations](https://docs.djangoproject.com/en/4.1/ref/django-admin/#django-admin-makemigrations).

# Context

During our 4/25 meeting, we thought through a basic shape of what these models may look like:
```js
const location = {
  latLong: ["lat", "long"],
  name: "Best Cafe",
  address: "123 Main St",
  hours: "Hopefully yelp has a standard",
  locationType: "cafe, restaurant",
  priceCategory: "$$",
  //   This is our word cloud
  tags: {
    // Categories of words
    // Could be built from whitelist
    // Categories map to sliders in app/quiz
    positive: { happy: 0.1, nice: 0.05 },
    // words have score of percentage of total words or per review
    quiet: {},
    negative: {},
    social: {},
  },
};

const exampleReview1 =
  "I had a great time at Best Cafe and was very happy with the service and the quality of the food";
const exampleReview2 =
  "I had a terrible time at Best Cafe and was very displeased with the service and the quality of the food";
const exampleReview3 =
  "I had an okay time at Best Cafe and was fine with the service and the quality of the food";

// From the examples, raw word count is less helpful since "quality" and "had" come up
// Rather we can have a set of keywords to parse for and evaulate how often they come up
// We can do this with regex patterns/putting keywords and phrase into regex

// We can also use the rating of the space to weight the results as well

// Ingest data from https://docs.developer.yelp.com/reference/v3_business_search
// Use bizId to get reviews: https://docs.developer.yelp.com/reference/v3_business_reviews
// Review has a url we could ideally scrape
// "Also, this probably comes as no surprise, but scraping yelp.com for data is against Yelp's ToS."
```

# Suggested solution (optional)

Read through the [django models](https://docs.djangoproject.com/en/4.2/topics/db/models/) and [geodjango models](https://docs.djangoproject.com/en/4.1/ref/contrib/gis/model-api/) documentations for direction and examples.

My (@travissouthard's) suggestion is to have the `tags` attribute of the `location` model be a foreign key to a model for `tags` specifically. Also that at least the `location` model would be a Geodjango model rather than a vanilla django model (e.g.: `from django.contrib.gis.db import models`)

**Comment by zimurgh** [comment]
I'll work on this if that's ok

**Comment by zimurgh** [comment]
#21
